### PR TITLE
hub.fish created in etc/

### PR DESCRIPTION
**Pull request by hasit**

### CODE REVIEW

**Comment by mislav** [comment]
:+1: 

After the fish script is working, we might want to [update the Homebrew formula](https://github.com/Homebrew/homebrew/blob/03e4c2a584189a2f3d184b4ddae879f1e1031456/Library/Formula/hub.rb#L24-L25) to be aware of its presence.

**Comment by hasit** [comment]
@mislav, what kind of basic functionalities would you like in the first fish script? I was thinking of the adding help, add, commit and push for now.

**Comment by mislav** [comment]
I was thinking of having basic support for all hub commands that are not git commands, i.e. those that don't extend and existing git command. Those are:

* `git create [NAME] [-p] [-d DESCRIPTION] [-h HOMEPAGE]`
* `git browse [-u] [[USER/]REPOSITORY] [SUBPAGE]`
* `git compare [-u] [USER] [[START...]END]`
* `git fork [--no-remote]`
* `git pull-request [-o|--browse] [-f] [-m MESSAGE|-F FILE|-i ISSUE|ISSUE-URL] [-b BASE] [-h HEAD]`
* `git ci-status [-v] [COMMIT]`

**Comment by mislav** [comment]
Notes from the video call we just had: it seems that the `-f` flag that disables file listing on <kbd>Tab</kbd> doesn't work for some reason, i.e. `hub fork <Tab>` still lists files in the current directory.

We will try to figure out why this happens, but for now just proceed with adding other commands and their flags.

**Comment by hasit** [comment]
I think I have a way around that. What I have in mind is:
`complete -c hub -n '__fish_hub_using_command fork' -a '(__fish_hub_suppress_files)' -d 'Do not show files'`
I'll try implementing the `__fish_hub_suppress_files` function and see how it works.

**Comment by mislav** [comment]
Looks great! Feel free to merge this PR into the "gsoc" branch (you can use the Merge Button) and start subsequent work in new PRs based on your "gsoc" branch, per my guidance document.

For example, the new topics that you might start on:

1. Context-aware completions for some argument types (file completion for `pull-request -F`, branch completion for `ci-status`, etc.)
2. Go program that takes in standard input and parses the list of command-line flags.

**Comment by hasit** [comment]
Thank you. Closing this and merging now.

**Pull request merged**
